DROP TABLE IF EXISTS INSTRUMENT_TICKS_DETAILS;

CREATE TABLE INSTRUMENT_TICKS_DETAILS(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  instrument VARCHAR(50) NOT NULL,
  price DECIMAL(20, 2) NOT NULL,
  instrument_timestamp TIMESTAMP NOT NULL
);


INSERT INTO INSTRUMENT_TICKS_DETAILS (ID, INSTRUMENT,PRICE, INSTRUMENT_TIMESTAMP) VALUES ( 100, 'IBM.M', 25.5, CURRENT_TIMESTAMP());
INSERT INTO INSTRUMENT_TICKS_DETAILS (ID, INSTRUMENT,PRICE, INSTRUMENT_TIMESTAMP) VALUES ( 101, 'IBM.M', 22.5, CURRENT_TIMESTAMP());
INSERT INTO INSTRUMENT_TICKS_DETAILS (ID, INSTRUMENT,PRICE, INSTRUMENT_TIMESTAMP) VALUES ( 103, 'IBM.M', 21.7, CURRENT_TIMESTAMP());
INSERT INTO INSTRUMENT_TICKS_DETAILS (ID, INSTRUMENT,PRICE, INSTRUMENT_TIMESTAMP) VALUES ( 104, 'IBM.M', 21.52, CURRENT_TIMESTAMP());
INSERT INTO INSTRUMENT_TICKS_DETAILS (ID, INSTRUMENT,PRICE, INSTRUMENT_TIMESTAMP) VALUES ( 105, 'IBM.M', 21.05, CURRENT_TIMESTAMP());
INSERT INTO INSTRUMENT_TICKS_DETAILS (ID, INSTRUMENT,PRICE, INSTRUMENT_TIMESTAMP) VALUES ( 106, 'IBM.M', 21.5, CURRENT_TIMESTAMP());
INSERT INTO INSTRUMENT_TICKS_DETAILS (ID, INSTRUMENT,PRICE, INSTRUMENT_TIMESTAMP) VALUES ( 107, 'IBM.M', 19.0, CURRENT_TIMESTAMP());
